i_want = ['London','Bei jing','Tokyo','Paris','ShangHai']
print(i_want)
print(sorted(i_want))
print(i_want)
print(sorted(i_want,reverse=True))
print(i_want)
i_want.reverse()
print(i_want)
i_want.reverse()
print(i_want)
i_want.sort()
print(i_want)
i_want.sort(reverse=True)
print(i_want)